from youtuber_api.main import app


def test_application_routes_can_be_constructed() -> None:
    paths = {route.path for route in app.routes}
    methods_by_path: dict[str, set[str]] = {}
    for route in app.routes:
        methods_by_path.setdefault(route.path, set()).update(getattr(route, "methods", set()) or set())
    assert "/api/health/ready" in paths
    assert "/api/v1/auth/logout" in paths
    assert "/api/v1/auth/totp/enroll" in paths
    assert "/api/v1/auth/totp/confirm" in paths
    assert "/api/v1/auth/totp/disable" in paths
    assert "/api/v1/auth/oidc/status" in paths
    assert "/api/v1/auth/oidc/configuration" in paths
    assert "/api/v1/auth/oidc/start" in paths
    assert "/api/v1/auth/oidc/callback" in paths
    assert "/api/v1/system/durability-probes" in paths
    assert "/api/v1/channel-profiles" in paths
    assert "PUT" in methods_by_path["/api/v1/channel-profiles/{profile_id}"]
    assert "DELETE" in methods_by_path["/api/v1/channel-profiles/{profile_id}"]
    assert "/api/v1/channel-profiles/archived" in paths
    assert "POST" in methods_by_path["/api/v1/channel-profiles/{profile_id}/restore"]
    assert "/api/v1/subject-profiles" in paths
    assert "PUT" in methods_by_path["/api/v1/subject-profiles/{profile_id}"]
    assert "DELETE" in methods_by_path["/api/v1/subject-profiles/{profile_id}"]
    assert "/api/v1/subject-profiles/archived" in paths
    assert "POST" in methods_by_path["/api/v1/subject-profiles/{profile_id}/restore"]
    assert "/api/v1/subject-profiles/{profile_id}/test-search-plan" in paths
    assert "/api/v1/subject-profiles/{profile_id}/schedule" in paths
    assert "/api/v1/subject-profiles/{profile_id}/schedule/reconcile" in paths
    assert "/api/v1/research/fixture-runs" in paths
    assert "/api/v1/research/live-discovery-runs" in paths
    assert "/api/v1/research/acquisition-runs" in paths
    assert "/api/v1/research/dossier-runs" in paths
    assert "/api/v1/research/runs/{workflow_id}/events" in paths
    assert "/api/v1/research/runs/{workflow_id}/logs" in paths
    assert "/api/v1/research/runs/{workflow_id}/cancel" in paths
    assert "/api/v1/research/runs/{workflow_id}/retry" in paths
    assert "/api/v1/research/sources" in paths
    assert "/api/v1/research/sources/{source_id}/preview" in paths
    assert "/api/v1/research/sources/{source_id}/index" in paths
    assert "/api/v1/research/source-relationships" in paths
    assert "/api/v1/research/opportunities/{opportunity_id}/decision" in paths
    assert "/api/v1/research/opportunities" in paths
    assert "/api/v1/research/dossiers/{dossier_id}" in paths
    assert "/api/v1/research/dossiers/{dossier_id}/review" in paths
    assert "/api/v1/research/claims/{claim_id}/review" in paths
    assert "/api/v1/providers" in paths
    assert "/api/v1/models" in paths
    assert "/api/v1/ai-usage" in paths
    assert "/api/v1/task-model-assignments/{task_type}" in paths
    assert "/api/v1/prompt-templates/{template_key}" in paths
    assert "/api/v1/editorial/script-runs" in paths
    assert "/api/v1/editorial/runs/{workflow_id}/events" in paths
    assert "/api/v1/editorial/runs/{workflow_id}/cancel" in paths
    assert "/api/v1/editorial/runs/{workflow_id}/retry" in paths
    assert "/api/v1/editorial/scripts/{script_id}" in paths
    assert "/api/v1/editorial/scripts/{script_id}/versions" in paths
    assert "/api/v1/editorial/scripts/{script_id}/verification-runs" in paths
    assert "/api/v1/editorial/scripts/{script_id}/regeneration-runs" in paths
    assert "/api/v1/editorial/scripts/{script_id}/approve" in paths
    assert "/api/v1/editorial/scripts/{script_id}/storyboard-runs" in paths
    assert "/api/v1/editorial/storyboards/{storyboard_id}" in paths
    assert "/api/v1/editorial/storyboards/{storyboard_id}/scenes/{scene_id}/lock" in paths
    assert "/api/v1/editorial/storyboards/{storyboard_id}/scenes/{scene_id}/versions" in paths
    assert "/api/v1/editorial/storyboards/{storyboard_id}/scenes/{scene_id}/alternative-runs" in paths
    assert "/api/v1/editorial/storyboards/{storyboard_id}/scenes/{scene_id}/alternatives" in paths
    assert "/api/v1/editorial/storyboards/{storyboard_id}/scenes/{scene_id}/alternatives/{alternative_id}/select" in paths
    assert "/api/v1/editorial/storyboards/{storyboard_id}/approve" in paths
    assert "/api/v1/publishing/configuration" in paths
    assert "/api/v1/publishing/oauth/start" in paths
    assert "/api/v1/publishing/oauth/callback" in paths
    assert "/api/v1/publishing/metadata" in paths
    assert "/api/v1/publishing/approvals" in paths
    assert "/api/v1/publishing/uploads" in paths
    assert "/api/v1/publishing/uploads/{publication_id}/reconcile" in paths
    assert "/api/v1/publishing/uploads/{publication_id}/schedule" in paths
    assert "/api/v1/optimization/analytics/snapshots" in paths
    assert "/api/v1/optimization/analytics/dashboard" in paths
    assert "/api/v1/optimization/benchmarks" in paths
    assert "/api/v1/optimization/recommendations/{recommendation_id}/decision" in paths
    assert "/api/v1/optimization/recommendations/{recommendation_id}/apply" in paths
    assert "/api/v1/optimization/freshness-checks" in paths
    assert "/api/v1/optimization/originality-reports" in paths
    assert "/api/v1/optimization/corrections" in paths
    assert "/api/v1/optimization/budgets/{scope}" in paths
    assert "/api/v1/optimization/budget-usage" in paths
    assert "/api/v1/optimization/operational-evidence" in paths
